server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auto_servis}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:nova_lozinka}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  jwt-secret: ${JWT_SECRET:dev-very-long-secret-at-least-32-chars}
